# .github/workflows/staging.yaml
name: 'Terraform - Staging'

on:
  push:
    branches:
    - dev-6
    paths: 
    - staging/**


permissions:
  contents: read
  pull-requests: write

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs: 
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: staging 

steps:
  - name: Checkout the repository to the runner
    uses: actions/checkout@v3

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ap-southeast-2

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2
